### ISSUE TITLE
Fails if cookies or data storage are disabled in the browser

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/resin-settings-storage#17]
I've tested this in both FF and Chrome.
We need to test to see if `localStorage` is available - similar to how the ngStorage module does it https://github.com/gsklee/ngStorage/blob/master/ngStorage.js#L21
Simply testing for the existence of `localStorage` returns
`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` in chrome and `SecurityError: The operation is insecure.`.
Both of these errors can halt operations, crashing your app.

**Comment by pimterry** [comment]
This was fixed ages ago, closing
